# 디렉토리 및 데이터 관련
data:
  dataset_name: "ogbg_code2"
  dir: "./"

# 모델 아키텍처 관련
model:
  hidden_dim: 64
  num_layers: 3
  dropout: 0.5 ######

# 학습 관련
train:
  weight_decay: 1e-5
  epochs: 50
  batch_size: 32
  num_vocab, max_seq_len = 5000, 5
  batch_size: 32
  lr: 1e-3
  num_workers: 4

cuda:
  cuda_number: 7