# 디렉토리 및 데이터 관련
data:
  dataset_name: "ogbg-ppa"
  dir: "./"

# 모델 아키텍처 관련
model:
  num_layers: 4
  num_sublayers: 2
  vn_residual: true
  vn_residual_alpha: 0.5
  backbone_residual: true

# 학습 관련
train:
  seed: 42
  weight_decay: 0.0001
  epochs: 150
  warmup_epochs: 5
  grad_clip: 1.0 # null 하면 취소
  ema_decay: null
  amp: true # GPU 최적화
  batch_size: 32
  max_seq_len : 5
  lr: 0.001
  num_workers: 4
  num_vocab: 5000
  emb_dim : 300
  max_depth : 20
  drop_ratio : 0.35
  
cuda:
  cuda_number: 8